-- Databricks notebook source
CREATE OR REPLACE TABLE gold.ans.market_share
USING DELTA AS (
  WITH TOTAL_BENEFICIARIOS AS (
    SELECT SUM(TOTAL_BENEFICIARIOS) AS TOTAL
    FROM gold.ans.num_beneficiarios
  )

  SELECT CD_OPERADORA, op.CNPJ, NM_RAZAO_SOCIAL, op.NOME_FANTASIA,
    ROUND(SUM(TOTAL_BENEFICIARIOS)*100/(SELECT TOTAL FROM TOTAL_BENEFICIARIOS), 2) AS MARKET_SHARE
  FROM gold.ans.num_beneficiarios AS nb
  LEFT JOIN silver.ans.operadoras AS op
  ON nb.CD_OPERADORA = op.REGISTRO_ANS
  GROUP BY CD_OPERADORA, NM_RAZAO_SOCIAL, op.NOME_FANTASIA, op.CNPJ
  ORDER BY MARKET_SHARE DESC
)
