-- Databricks notebook source
CREATE OR REPLACE TABLE gold.ans.market_share
USING DELTA AS (
  WITH TOTAL_BENEFICIARIOS AS (
    SELECT SUM(NUM_BENEFICIARIOS) AS TOTAL
    FROM gold.ans.num_beneficiarios_2024_05
  )

  SELECT CD_OPERADORA, NM_RAZAO_SOCIAL, 
    ROUND(SUM(NUM_BENEFICIARIOS)*100/(SELECT TOTAL FROM TOTAL_BENEFICIARIOS), 2) AS MARKET_SHARE
  FROM gold.ans.num_beneficiarios_2024_05
  GROUP BY CD_OPERADORA, NM_RAZAO_SOCIAL
  ORDER BY MARKET_SHARE DESC
)
